<?xml version="1.0" encoding="UTF-8"?>
<testsuite hostname="VASANTHA" name="test.SampleTest.DataProviderExample" tests="2" failures="1" timestamp="26 Jun 2011 04:19:45 GMT" time="40.578" errors="0">
  <testcase name="testDataProviderExample on instance null(test.SampleTest.DataProviderExample)" time="15.593" classname="test.SampleTest.DataProviderExample"/>
  <testcase name="testDataProviderExample on instance null(test.SampleTest.DataProviderExample)" time="5.672" classname="test.SampleTest.DataProviderExample">
    <failure type="com.thoughtworks.selenium.SeleniumException" message="ERROR: Element xpath=/descendant::a[text()=&amp;apos;Kung fu Panda 2&amp;apos;] not found">
      <![CDATA[com.thoughtworks.selenium.SeleniumException: ERROR: Element xpath=/descendant::a[text()='Kung fu Panda 2'] not found
	at com.thoughtworks.selenium.HttpCommandProcessor.throwAssertionFailureExceptionOrError(HttpCommandProcessor.java:97)
	at com.thoughtworks.selenium.HttpCommandProcessor.doCommand(HttpCommandProcessor.java:91)
	at com.thoughtworks.selenium.DefaultSelenium.click(DefaultSelenium.java:167)
	at test.SampleTest.DataProviderExample.testDataProviderExample(DataProviderExample.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:74)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:673)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:846)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1170)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.runWorkers(TestRunner.java:1125)
	at org.testng.TestRunner.privateRun(TestRunner.java:749)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:317)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:312)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:274)
	at org.testng.SuiteRunner.run(SuiteRunner.java:223)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:995)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:920)
	at org.testng.TestNG.run(TestNG.java:856)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:110)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:174)
]]>
    </failure>
  </testcase>
</testsuite>
